/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance { 'user' : User, 'percentage' : bigint }
export interface Attendance__1 {
  'present' : bigint,
  'late' : bigint,
  'absent' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Id { 'creator' : Principal, 'number' : bigint }
export interface Material {
  'id' : Id,
  'url' : string,
  'title' : string,
  'subject' : string,
  'file' : ExternalBlob,
  'description' : string,
  'author' : User,
  'materialType' : MaterialType,
  'uploadedAt' : Time,
}
export type MaterialType = { 'pdf' : null } |
  { 'link' : null } |
  { 'note' : null };
export type Role = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export type Time = bigint;
export interface User {
  'id' : Id,
  'userRole' : Role,
  'subjects' : Array<string>,
  'name' : string,
  'email' : string,
  'attendance' : Attendance__1,
  'phone' : bigint,
  'photo' : ExternalBlob,
  'parentOf' : [] | [Id],
}
export interface UserProfile {
  'subjects' : Array<string>,
  'appRole' : Role,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : bigint,
  'parentOf' : [] | [Id],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMaterial' : ActorMethod<[Material], Material>,
  'getAllAttendances' : ActorMethod<[], Array<Attendance>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAttendance' : ActorMethod<[], [] | [Attendance]>,
  'getStudentAttendance' : ActorMethod<[Id], [] | [Attendance]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[Id, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];