/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Record({ 'creator' : IDL.Principal, 'number' : IDL.Nat });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const Attendance__1 = IDL.Record({
  'present' : IDL.Nat,
  'late' : IDL.Nat,
  'absent' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : Id,
  'userRole' : Role,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'attendance' : Attendance__1,
  'phone' : IDL.Nat,
  'photo' : ExternalBlob,
  'parentOf' : IDL.Opt(Id),
});
export const MaterialType = IDL.Variant({
  'pdf' : IDL.Null,
  'link' : IDL.Null,
  'note' : IDL.Null,
});
export const Time = IDL.Int;
export const Material = IDL.Record({
  'id' : Id,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'author' : User,
  'materialType' : MaterialType,
  'uploadedAt' : Time,
});
export const Attendance = IDL.Record({ 'user' : User, 'percentage' : IDL.Nat });
export const UserProfile = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'appRole' : Role,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Nat,
  'parentOf' : IDL.Opt(Id),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMaterial' : IDL.Func([Material], [Material], []),
  'getAllAttendances' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAttendance' : IDL.Func([], [IDL.Opt(Attendance)], ['query']),
  'getStudentAttendance' : IDL.Func([Id], [IDL.Opt(Attendance)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([Id, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Record({ 'creator' : IDL.Principal, 'number' : IDL.Nat });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const Attendance__1 = IDL.Record({
    'present' : IDL.Nat,
    'late' : IDL.Nat,
    'absent' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : Id,
    'userRole' : Role,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'attendance' : Attendance__1,
    'phone' : IDL.Nat,
    'photo' : ExternalBlob,
    'parentOf' : IDL.Opt(Id),
  });
  const MaterialType = IDL.Variant({
    'pdf' : IDL.Null,
    'link' : IDL.Null,
    'note' : IDL.Null,
  });
  const Time = IDL.Int;
  const Material = IDL.Record({
    'id' : Id,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'author' : User,
    'materialType' : MaterialType,
    'uploadedAt' : Time,
  });
  const Attendance = IDL.Record({ 'user' : User, 'percentage' : IDL.Nat });
  const UserProfile = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'appRole' : Role,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Nat,
    'parentOf' : IDL.Opt(Id),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMaterial' : IDL.Func([Material], [Material], []),
    'getAllAttendances' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAttendance' : IDL.Func([], [IDL.Opt(Attendance)], ['query']),
    'getStudentAttendance' : IDL.Func([Id], [IDL.Opt(Attendance)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([Id, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };